name: tests

on:
  - pull_request
  - workflow_dispatch

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - name: Run Pest tests
        run: ./vendor/bin/pest
