name: tests

permissions:
  contents: write

on:
  - pull_request
  - workflow_dispatch

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - name: Set directory permissions
        run: sudo chmod -R 777 vendor/composer
      - name: Run Pest tests
        run: ./vendor/bin/pest
