name: analyze

on:
  - pull_request
  - workflow_dispatch

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6 # or alternative dependency management
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run Pest tests
        run: ./vendor/bin/pest
