name: format

on:
  - pull_request
  - workflow_dispatch

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@latest
        with:
          configPath: "./pint.json"
          verboseMode: true
          onlyDirty: true
